version: '3.9'

services:
  app:
    build: .
    container_name: app
    environment:
      SPRING_PROFILES_ACTIVE: local
    networks:
      - groceries-network

  postgres:
    image: postgres:14.3-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: groceries
      POSTGRES_PASSWORD: groceries
      POSTGRES_USER: groceries
    volumes:
      - ./initdb.sh:/db/init/initdatabase.sql
    networks:
      - groceries-network

networks:
  groceries-network:
    name: groceries